### ISSUE TITLE
New design!

### ISSUE THREAD

**Issue by lislis** [rubycorns/rorganize.it#415]
I have asked the ever awesome @saltinejustine to take a look at our little app and it's :boom: :sparkles: 
![rorganize_it](https://cloud.githubusercontent.com/assets/1006478/12296540/a900c99c-ba08-11e5-98e9-29aa438364e6.png)
![rorganize-it-brand](https://cloud.githubusercontent.com/assets/1006478/12296541/a92b64c2-ba08-11e5-8abf-8ef12b6f2c4a.png)
What do y'all think?

**Comment by berlintam** [comment]
LOVE
IT
!

**Comment by saltinejustine** [comment]
Thanks for inviting me to participate @lislis. I'll work on more screens this week — this is just what I had time to do last night after you asked me. :two_hearts:

**Comment by lislis** [comment]
@saltinejustine I hope you realize that you're a Rubycorn now as well ;)

**Comment by saltinejustine** [comment]
@lislis HOORAY! :sparkles:

**Comment by alicetragedy** [comment]
soooooo prettyyyyyyy :sparkles: :sparkling_heart: :two_hearts:

**Comment by sareg0** [comment]
wwhhhaaatt!! I can't even!!
![](http://memesvault.com/wp-content/uploads/Happy-Crying-Face-Meme-04.png)
It's so purdy, and I love it. Thank you @saltinejustine

**Comment by BriocheBerlin** [comment]
This is great :heart_eyes_cat:

**Comment by saltinejustine** [comment]
## Update to Groups
![rorganize-it-groups](https://cloud.githubusercontent.com/assets/823381/12429908/c6df9d9c-beba-11e5-987a-971eec85d9e0.png)

## Added screen for People
![rorganize-people](https://cloud.githubusercontent.com/assets/823381/12429909/c6e12d38-beba-11e5-9b8c-462bfe652c5d.png)

**Comment by sareg0** [comment]
okay, I would like to have this issue along with @berlintam. Peeps can also join us if they feel like it. We're gonna get underway this evening.

**Comment by sareg0** [comment]
@saltinejustine could we trouble you to send us the png/psd/files for the logo?
Can you do it here, or did you wanna send via email?

**Comment by lislis** [comment]
svg!

**Comment by PragTob** [comment]
Also like it a lot, thanks @saltinejustine !

Only thing from my side I'd maybe a bit of grey with red to look more "friendly" but I'm no designer by any measure :D 

Thanks again! :heart: 

Tobi

**Comment by saltinejustine** [comment]
Can't add SVGs in comments on Github. :wink: But I'll email it. Who should I direct that email to?

Otherwise colors are:
`$ salmon-pink: #e2635a`
`$ petal-pink: #f2bbae`
`$ ochre-yellow: #ffc842`
`$ daisy-yellow: #ffe6b2`
`$ onyx-grey: 606161`
`$ limestone-grey: #a09f9f`

**Comment by PragTob** [comment]
Can you email Sara, she'd love to have it? :) Do you have her email?

**Comment by saltinejustine** [comment]
:white_check_mark: Sent!

**Comment by PragTob** [comment]
Thanks!

**Comment by sareg0** [comment]
Thank you @saltinejustine!! Oh, and what are the fonts you're going with, and the typographic heirarchy?

**Comment by saltinejustine** [comment]
Hey @sareg0 sorry about not replying sooner, I've had kind of a hectic week. Here are some of the styles in that design. I'll try and get you some more this weekend before your next Rubycorns meeting 💕 

```css
body {
font-family: 'Lato', Helvetica, sans-serif;
/* Lato is a free webfont and can be found using Google Fonts */
font-size: 18px;
color: #484748;
line-height: 1.5em;
}

h1, h2, h3 {
font-size: 25px;
}

h1, h2 {
font-wight: 700;
}

h1 {
color: #ffc842;
border-bottom: solid 1px;
}

h2 {
color: #a09f9f;
}

h3 {
font-weight: 400;
color: #aaa6a6;
border-bottom: solid 1px;
}
```
